name: Build and Release Java Project

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile Java code
        run: |
          mkdir -p out
          javac -classpath ./lib/forms_rt.jar -d out *.java

      - name: Package into JAR
        run: |
          mkdir -p build
          echo "Main-Class: Main" > manifest.txt
          jar cfm build/MultiBal.jar manifest.txt -C out . -C lib forms_rt.jar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: MultiBal
          path: build/MultiBal.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: MultiBal
          path: build

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.${{ github.run_number }}  # Auto-incremented tag
          name: "MultiBal Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
          artifacts: "build/MultiBal.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
